### PR TITLE
feat: add request address to context

### PR DESCRIPTION
**Pull request by crowlKats**
Let me know if you'd rather want the address be part of `requestEvent`

### CODE REVIEW

**Review by kitsonk — COMMENTED** [review]
A couple of thoughts...

- Should it be optional? (and return `undefined` in the context), I guess though even on Node.js you would want it to be there.
- I have tried to decouple as much from dependency on specific Deno types (see: `types.d.ts`) which makes it easier to even be version agnostic as well as maybe target other runtimes, so adding `Addr` to `types.d.ts` would be preferred.
- Feels like `router.handle()` should be `(request, init)` now instead, but I can take care of that later if you want.

**Comment by crowlKats** [comment]
> Should it be optional? (and return `undefined` in the context), I guess though even on Node.js you would want it to be there.

I don't think so; as you say, even nodejs would have it. Though I don't mind making it optional if you prefer, doesnt make much of a difference to me.

> I have tried to decouple as much from dependency on specific Deno types (see: `types.d.ts`) which makes it easier to even be version agnostic as well as maybe target other runtimes, so adding `Addr` to `types.d.ts` would be preferred.

done

> Feels like `router.handle()` should be `(request, init)` now instead, but I can take care of that later if you want.

sure, took care of it

**Review by kitsonk — APPROVED** [review]
LGTM

**Comment by kitsonk** [comment]
This is available in 0.3.0: https://deno.land/x/acorn@0.3.0

**Pull request merged**
